/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardProjectIdRouteImport } from './routes/dashboard.$projectId'
import { Route as DashboardProjectIdIndexRouteImport } from './routes/dashboard.$projectId.index'
import { Route as DashboardProjectIdTabPathRouteImport } from './routes/dashboard.$projectId.$tabPath'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectIdRoute = DashboardProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectIdIndexRoute = DashboardProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardProjectIdRoute,
} as any)
const DashboardProjectIdTabPathRoute =
  DashboardProjectIdTabPathRouteImport.update({
    id: '/$tabPath',
    path: '/$tabPath',
    getParentRoute: () => DashboardProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/$projectId': typeof DashboardProjectIdRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$projectId/$tabPath': typeof DashboardProjectIdTabPathRoute
  '/dashboard/$projectId/': typeof DashboardProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/$projectId/$tabPath': typeof DashboardProjectIdTabPathRoute
  '/dashboard/$projectId': typeof DashboardProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/$projectId': typeof DashboardProjectIdRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$projectId/$tabPath': typeof DashboardProjectIdTabPathRoute
  '/dashboard/$projectId/': typeof DashboardProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/$projectId'
    | '/dashboard/'
    | '/dashboard/$projectId/$tabPath'
    | '/dashboard/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/$projectId/$tabPath'
    | '/dashboard/$projectId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/$projectId'
    | '/dashboard/'
    | '/dashboard/$projectId/$tabPath'
    | '/dashboard/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$projectId': {
      id: '/dashboard/$projectId'
      path: '/$projectId'
      fullPath: '/dashboard/$projectId'
      preLoaderRoute: typeof DashboardProjectIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$projectId/': {
      id: '/dashboard/$projectId/'
      path: '/'
      fullPath: '/dashboard/$projectId/'
      preLoaderRoute: typeof DashboardProjectIdIndexRouteImport
      parentRoute: typeof DashboardProjectIdRoute
    }
    '/dashboard/$projectId/$tabPath': {
      id: '/dashboard/$projectId/$tabPath'
      path: '/$tabPath'
      fullPath: '/dashboard/$projectId/$tabPath'
      preLoaderRoute: typeof DashboardProjectIdTabPathRouteImport
      parentRoute: typeof DashboardProjectIdRoute
    }
  }
}

interface DashboardProjectIdRouteChildren {
  DashboardProjectIdTabPathRoute: typeof DashboardProjectIdTabPathRoute
  DashboardProjectIdIndexRoute: typeof DashboardProjectIdIndexRoute
}

const DashboardProjectIdRouteChildren: DashboardProjectIdRouteChildren = {
  DashboardProjectIdTabPathRoute: DashboardProjectIdTabPathRoute,
  DashboardProjectIdIndexRoute: DashboardProjectIdIndexRoute,
}

const DashboardProjectIdRouteWithChildren =
  DashboardProjectIdRoute._addFileChildren(DashboardProjectIdRouteChildren)

interface DashboardRouteChildren {
  DashboardProjectIdRoute: typeof DashboardProjectIdRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardProjectIdRoute: DashboardProjectIdRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
