export const demoEvents = [
  [
    "user_100",
    "session_100",
    "kakao",
    "campaign_fresh_food_01",
    "chicken_breast_001",
    "fresh_food",
    "30s",
    "male",
    "mobile",
    9900,
    "out_of_stock",
    "수도권",
    "닭가슴살 품절",
    ["page_view", "product_view", "add_to_cart", "checkout_start"]
  ],
  [
    "user_101",
    "session_101",
    "kakao",
    "campaign_fresh_food_01",
    "salad_kit_001",
    "fresh_food",
    "30s",
    "female",
    "mobile",
    12900,
    "in_stock",
    "수도권",
    "모바일 재방문",
    ["page_view", "product_view", "add_to_cart", "checkout_start", "purchase"]
  ],
  [
    "user_102",
    "session_102",
    "naver",
    "campaign_milk_kit_01",
    "milk_kit_001",
    "milk_kit",
    "30s",
    "female",
    "mobile",
    24900,
    "in_stock",
    "부산/경남",
    "쿠폰 사용",
    ["page_view", "product_view", "add_to_cart", "checkout_start", "purchase"]
  ],
  [
    "user_103",
    "session_103",
    "instagram",
    "campaign_dessert_01",
    "dessert_box_001",
    "dessert",
    "20s",
    "female",
    "mobile",
    17900,
    "in_stock",
    "대구/경북",
    "가격 민감",
    ["page_view", "product_view", "leave_page"]
  ],
  [
    "user_104",
    "session_104",
    "community",
    "campaign_jeongyuk_01",
    "beef_pack_001",
    "butcher",
    "40s",
    "female",
    "desktop",
    48900,
    "in_stock",
    "충청권",
    "고가 객단가",
    ["page_view", "product_view", "add_to_cart"]
  ],
  [
    "user_105",
    "session_105",
    "app_push",
    "campaign_health_01",
    "protein_001",
    "health_food",
    "40s",
    "female",
    "mobile",
    38900,
    "in_stock",
    "수도권",
    "성과 확장 후보",
    ["page_view", "product_view", "add_to_cart", "checkout_start", "purchase"]
  ],
  [
    "user_106",
    "session_106",
    "app_push",
    "campaign_health_01",
    "protein_001",
    "health_food",
    "40s",
    "female",
    "mobile",
    38900,
    "in_stock",
    "수도권",
    "성과 확장 후보",
    ["page_view", "product_view", "add_to_cart", "checkout_start", "purchase"]
  ],
  [
    "user_107",
    "session_107",
    "naver",
    "campaign_fresh_food_02",
    "fish_001",
    "fresh_food",
    "40s",
    "male",
    "desktop",
    29900,
    "in_stock",
    "강원/제주",
    "결제 정보 입력 이탈",
    ["page_view", "product_view", "add_to_cart", "checkout_start"]
  ],
  [
    "user_108",
    "session_108",
    "kakao",
    "campaign_fresh_food_01",
    "chicken_breast_001",
    "fresh_food",
    "30s",
    "male",
    "mobile",
    9900,
    "out_of_stock",
    "수도권",
    "닭가슴살 품절",
    ["page_view", "product_view", "add_to_cart"]
  ],
  [
    "user_109",
    "session_109",
    "sms",
    "campaign_coupon_01",
    "lunch_box_001",
    "fresh_food",
    "50s",
    "male",
    "tablet",
    15900,
    "in_stock",
    "호남권",
    "메시지 클릭",
    ["page_view", "product_view", "add_to_cart", "checkout_start", "purchase"]
  ]
] as const;
